steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-pull'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'docker pull us-central1-docker.pkg.dev/starful-258005/oksushi-repo/oksushi:latest || exit 0'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-build'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/starful-258005/oksushi-repo/oksushi'
      - '--cache-from'
      - 'us-central1-docker.pkg.dev/starful-258005/oksushi-repo/oksushi:latest'
      - '.'
    waitFor: ['docker-pull']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-push'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/starful-258005/oksushi-repo/oksushi'
    waitFor: ['docker-build']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'oksushi'
      - '--image=us-central1-docker.pkg.dev/starful-258005/oksushi-repo/oksushi'
      - '--region=us-central1'
      - '--platform=managed'
      - '--port=8080'
      - '--memory=1Gi'
      - '--remove-env-vars=MAPS_API_KEY'
      - '--set-secrets=MAPS_API_KEY=MAPS_API_KEY:latest'
      - '--allow-unauthenticated'
    waitFor: ['docker-push']

images:
  - 'us-central1-docker.pkg.dev/starful-258005/oksushi-repo/oksushi'